# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

# HTTP lookup fails on GitHub and the -skip flag is broken for examples now.
# https://github.com/golang/go/issues/61482
# Omit package didweb entirely until any one of the preceding issues got fixed.
    - name: Test
      run: go test -skip didweb -v ./...
